# Generated by Django 5.1.7 on 2025-07-22 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseDeDatosBia',
            fields=[
                ('id_pago_unico', models.CharField(max_length=50)),
                ('propietario', models.CharField(max_length=100)),
                ('entidad_original_1', models.CharField(max_length=100)),
                ('entidad_original_2', models.CharField(max_length=100)),
                ('grupo', models.CharField(max_length=100)),
                ('tramo', models.CharField(max_length=100)),
                ('comision', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dni', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cuit', models.CharField(max_length=20)),
                ('nombre_apellido', models.CharField(max_length=200)),
                ('fecha_apertura', models.DateField(blank=True, null=True)),
                ('fecha_deuda', models.DateField(blank=True, null=True)),
                ('saldo_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('saldo_exigible', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('interes_diario', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('interes_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('saldo_actualizado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cancel_min', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cod_rp', models.CharField(blank=True, max_length=50, null=True)),
                ('agencia', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_estado', models.CharField(blank=True, max_length=50, null=True)),
                ('tel_1', models.CharField(blank=True, max_length=50, null=True)),
                ('tel_2', models.CharField(blank=True, max_length=50, null=True)),
                ('tel_3', models.CharField(blank=True, max_length=50, null=True)),
                ('tel_4', models.CharField(blank=True, max_length=50, null=True)),
                ('tel_5', models.CharField(blank=True, max_length=50, null=True)),
                ('mail_1', models.EmailField(blank=True, max_length=100, null=True)),
                ('mail_2', models.EmailField(blank=True, max_length=100, null=True)),
                ('mail_3', models.EmailField(blank=True, max_length=100, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('pago_acumulado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('ultima_fecha_pago', models.DateField(blank=True, null=True)),
                ('fecha_plan', models.DateField(blank=True, null=True)),
                ('anticipo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cuotas', models.IntegerField(blank=True, null=True)),
                ('importe', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_plan', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='certificados_generados/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.OneToOneField(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, to='certificado_ldd.basededatosbia')),
            ],
            options={
                'db_table': 'certificate',
            },
        ),
    ]
