# Generated by Django 5.1.7 on 2025-08-25 22:56

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga_datos', '0001_initial'),
        ('certificado_ldd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='client',
            field=models.OneToOneField(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='carga_datos.basededatosbia'),
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('responsable', models.CharField(blank=True, default='', max_length=255)),
                ('cargo', models.CharField(blank=True, default='', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_entidades/')),
                ('firma', models.ImageField(blank=True, null=True, upload_to='firmas_entidades/')),
                ('razon_social', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), name='uq_entidad_nombre_ci')],
            },
        ),
        migrations.DeleteModel(
            name='BaseDeDatosBia',
        ),
    ]
