# Generated by Django 5.1.7 on 2025-08-04 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga_datos', '0001_initial'),
        ('certificado_ldd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='client',
            field=models.OneToOneField(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, to='carga_datos.basededatosbia'),
        ),
        migrations.DeleteModel(
            name='BaseDeDatosBia',
        ),
    ]
