# Generated by Django 5.1.7 on 2025-08-05 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificado_ldd', '0002_alter_certificate_client_delete_basededatosbia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_entidades/')),
                ('firma', models.ImageField(blank=True, null=True, upload_to='firmas_entidades/')),
                ('responsable', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('razon_social', models.CharField(max_length=200)),
            ],
        ),
    ]
