# Generated by Django 5.1.7 on 2025-08-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificado_ldd', '0003_entidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='razon_social',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
