# Generated by Django 5.1.7 on 2025-08-19 03:47

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificado_ldd', '0004_alter_entidad_razon_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='cargo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='razon_social',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='responsable',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='entidad',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), name='uq_entidad_nombre_ci', violation_error_message='Ya existe una entidad con ese nombre (sin distinguir mayúsculas/minúsculas).'),
        ),
    ]
