# Generated by Django 5.1.7 on 2025-08-20 03:40

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificado_ldd', '0005_alter_entidad_cargo_alter_entidad_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='entidad',
            name='uq_entidad_nombre_ci',
        ),
        migrations.AlterField(
            model_name='entidad',
            name='cargo',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='responsable',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='entidad',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), name='uq_entidad_nombre_ci'),
        ),
    ]
