# Generated by Django 5.1.7 on 2025-08-25 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseDeDatosBia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_pago_unico', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('creditos', models.CharField(blank=True, max_length=255, null=True)),
                ('propietario', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('entidadoriginal', models.CharField(blank=True, max_length=255, null=True)),
                ('entidadinterna', models.CharField(db_index=True, max_length=255)),
                ('grupo', models.CharField(blank=True, max_length=50, null=True)),
                ('tramo', models.CharField(blank=True, max_length=50, null=True)),
                ('comision', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('dni', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('cuit', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_apellido', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_apertura', models.DateField(blank=True, null=True)),
                ('fecha_deuda', models.DateField(blank=True, null=True)),
                ('saldo_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('saldo_exigible', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('interes_diario', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('interes_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('saldo_actualizado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cancel_min', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_rp', models.CharField(blank=True, max_length=50, null=True)),
                ('agencia', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_estado', models.CharField(blank=True, max_length=50, null=True)),
                ('tel1', models.CharField(blank=True, max_length=50, null=True)),
                ('tel2', models.CharField(blank=True, max_length=50, null=True)),
                ('tel3', models.CharField(blank=True, max_length=50, null=True)),
                ('tel4', models.CharField(blank=True, max_length=50, null=True)),
                ('tel5', models.CharField(blank=True, max_length=50, null=True)),
                ('mail1', models.EmailField(blank=True, max_length=254, null=True)),
                ('mail2', models.EmailField(blank=True, max_length=254, null=True)),
                ('mail3', models.EmailField(blank=True, max_length=254, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('pago_acumulado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('ultima_fecha_pago', models.DateField(blank=True, null=True)),
                ('fecha_plan', models.DateField(blank=True, null=True)),
                ('anticipo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cuotas', models.IntegerField(blank=True, null=True)),
                ('importe', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_plan', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'db_bia',
                'managed': True,
            },
        ),
    ]
