# Generated by Django 5.1.7 on 2025-08-05 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga_datos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basededatosbia',
            name='entidadinterna',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='basededatosbia',
            name='id_pago_unico',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
