# Generated by Django 5.1.7 on 2025-08-25 22:56

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga_datos', '0001_initial'),
        ('certificado_ldd', '0002_alter_certificate_client_entidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basededatosbia',
            name='entidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='certificado_ldd.entidad'),
        ),
        migrations.AddIndex(
            model_name='basededatosbia',
            index=models.Index(django.db.models.functions.text.Lower('propietario'), name='idx_bdb_prop_lower'),
        ),
        migrations.AddIndex(
            model_name='basededatosbia',
            index=models.Index(django.db.models.functions.text.Lower('entidadinterna'), name='idx_bdb_entint_lower'),
        ),
    ]
