# Generated by Django 5.1.7 on 2025-09-04 23:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga_datos', '0002_basededatosbia_entidad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(blank=True, default='', max_length=255)),
                ('file_hash', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('ready_to_commit', 'Ready to commit'), ('committed', 'Committed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], db_index=True, default='ready_to_commit', max_length=32)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bulk_job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(db_index=True, max_length=128)),
                ('business_key', models.CharField(db_index=True, max_length=255)),
                ('field', models.CharField(db_index=True, max_length=128)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('action', models.CharField(choices=[('UPDATE', 'Update'), ('INSERT', 'Insert'), ('DELETE', 'Delete')], max_length=16)),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_audit_events', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='carga_datos.bulkjob')),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-ts'],
            },
        ),
        migrations.CreateModel(
            name='StagingBulkChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_key', models.CharField(max_length=255)),
                ('op', models.CharField(choices=[('UPDATE', 'Update'), ('INSERT', 'Insert'), ('DELETE', 'Delete'), ('NOCHANGE', 'No change')], default='UPDATE', max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('can_apply', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staging_rows', to='carga_datos.bulkjob')),
            ],
            options={
                'db_table': 'staging_bulk_change',
                'ordering': ['business_key'],
            },
        ),
        migrations.AddIndex(
            model_name='bulkjob',
            index=models.Index(fields=['status', 'created_at'], name='bulk_job_status_1d781d_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkjob',
            index=models.Index(fields=['file_hash'], name='bulk_job_file_ha_e8fd2f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['table_name', 'business_key'], name='audit_log_table_n_3ff0f3_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['job'], name='audit_log_job_id_b0e09a_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['ts'], name='audit_log_ts_18959c_idx'),
        ),
        migrations.AddIndex(
            model_name='stagingbulkchange',
            index=models.Index(fields=['job', 'business_key'], name='staging_bul_job_id_2d3f9a_idx'),
        ),
        migrations.AddIndex(
            model_name='stagingbulkchange',
            index=models.Index(fields=['op'], name='staging_bul_op_21e06a_idx'),
        ),
        migrations.AddIndex(
            model_name='stagingbulkchange',
            index=models.Index(fields=['can_apply'], name='staging_bul_can_app_c7667e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stagingbulkchange',
            unique_together={('job', 'business_key')},
        ),
    ]
