# Generated by Django 5.1.7 on 2025-08-08 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carga_datos', '0002_alter_basededatosbia_entidadinterna_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basededatosbia',
            options={},
        ),
        migrations.AlterModelTable(
            name='basededatosbia',
            table=None,
        ),
    ]
