# Generated by Django 5.1.7 on 2025-08-08 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carga_datos', '0003_alter_basededatosbia_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basededatosbia',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='basededatosbia',
            table='db_bia',
        ),
    ]
