# Generated by Django 5.1.7 on 2025-09-07 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga_datos', '0003_bulkjob_auditlog_stagingbulkchange_and_more'),
        ('certificado_ldd', '0002_alter_certificate_client_entidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessKeyCounter',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('last_value', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'business_key_counter',
            },
        ),
        migrations.AddConstraint(
            model_name='basededatosbia',
            constraint=models.CheckConstraint(condition=models.Q(('id_pago_unico__regex', '^\\d+$'), ('id_pago_unico__isnull', True), _connector='OR'), name='id_pago_unico_digits_or_null'),
        ),
    ]
