# Generated by Django 5.1.7 on 2025-09-08 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga_datos', '0004_businesskeycounter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basededatosbia',
            name='id_pago_unico',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
