# Generated by Django 5.1.7 on 2025-08-19 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga_datos', '0004_alter_basededatosbia_options_and_more'),
        ('certificado_ldd', '0005_alter_entidad_cargo_alter_entidad_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basededatosbia',
            name='entidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='certificado_ldd.entidad'),
        ),
    ]
