# Generated by Django 5.1.7 on 2025-08-20 03:40

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga_datos', '0005_basededatosbia_entidad'),
        ('certificado_ldd', '0006_remove_entidad_uq_entidad_nombre_ci_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basededatosbia',
            name='creditos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basededatosbia',
            name='entidadinterna',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='basededatosbia',
            name='propietario',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='basededatosbia',
            index=models.Index(django.db.models.functions.text.Lower('propietario'), name='idx_bdb_prop_lower'),
        ),
        migrations.AddIndex(
            model_name='basededatosbia',
            index=models.Index(django.db.models.functions.text.Lower('entidadinterna'), name='idx_bdb_entint_lower'),
        ),
    ]
