# Generated by Django 5.1.7 on 2025-09-18 23:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga_datos', '0005_alter_basededatosbia_id_pago_unico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basededatosbia',
            name='fecha_apertura',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
    ]
