# Generated by Django 5.1.7 on 2025-09-20 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carga_datos', '0006_alter_basededatosbia_fecha_apertura'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basededatosbia',
            options={'managed': True, 'permissions': [('can_manage_entities', 'Puede gestionar Entidades'), ('can_upload_excel', 'Puede cargar Excel'), ('can_bulk_modify', 'Puede Modificar Masivo'), ('can_view_clients', 'Puede ver/consultar clientes y descargas')]},
        ),
    ]
