# Generated by Django 5.1.7 on 2025-11-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga_datos', '0008_exportjobbia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exportjobbia',
            options={},
        ),
        migrations.RemoveField(
            model_name='exportjobbia',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='exportjobbia',
            name='file_url',
        ),
        migrations.RemoveField(
            model_name='exportjobbia',
            name='filters',
        ),
        migrations.RemoveField(
            model_name='exportjobbia',
            name='processed_rows',
        ),
        migrations.RemoveField(
            model_name='exportjobbia',
            name='status',
        ),
        migrations.AddField(
            model_name='exportjobbia',
            name='estado',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('RUNNING', 'En proceso'), ('DONE', 'Completado'), ('FAILED', 'Error')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='exportjobbia',
            name='file_path',
            field=models.CharField(blank=True, default='', help_text="Ruta relativa dentro de MEDIA_ROOT, por ejemplo 'exports/db_bia_20251129.csv'", max_length=500),
        ),
        migrations.AddField(
            model_name='exportjobbia',
            name='filename',
            field=models.CharField(blank=True, default='', help_text='Nombre del archivo descargable (ej: db_bia_20251129_120000.csv)', max_length=255),
        ),
        migrations.AddField(
            model_name='exportjobbia',
            name='filtro_dni',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='exportjobbia',
            name='filtro_id_pago_unico',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='exportjobbia',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exportjobbia',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exportjobbia',
            name='total_rows',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
