name: Build and Deploy Frontend (SWA)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy with Oryx (custom build command, tolerates warnings)
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "frontend"          # aquí está package.json + staticwebapp.config.json
          output_location: "build"          # carpeta que genera npm run build
          config_file_location: "frontend"  # la config vive en frontend/staticwebapp.config.json
          app_build_command: "CI='' npm ci && CI='' npm run build"
