name: Build and Deploy Frontend (SWA)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Usamos la acción de SWA pero con "app_build_command" propio
      # para desactivar CI y que no corte por warnings de ESLint.
      - name: Deploy via SWA Action (custom build)
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "frontend"   # aquí vive tu package.json y staticwebapp.config.json
          output_location: "build"   # carpeta que crea "npm run build"
          app_build_command: "CI='' npm ci && CI='' npm run build"
