name: Build and Deploy Frontend (SWA) - Prebuilt

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Build and include SWA config
        working-directory: frontend
        env:
          CI: ""
        run: |
          npm ci
          npm run build
          cp staticwebapp.config.json build/
          ls -la build | grep staticwebapp.config.json || (echo "Config no encontrada en build/"; exit 1)

      - name: Deploy prebuilt artifact to SWA (skip Oryx)
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_artifact_location: "frontend/build"
          config_file_location: "frontend/build"
          skip_app_build: true
