name: Build and Deploy Frontend (SWA) - Prebuilt

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Build (tolerate warnings) + include SWA config
        working-directory: frontend
        env:
          CI: ""   # evita que CRA corte por warnings
        run: |
          npm ci
          npm run build
          # Copiar la config al artefacto (raíz de build/)
          cp staticwebapp.config.json build/
          # Verificar que entró al artefacto
          ls -la build | grep staticwebapp.config.json || (echo "Config no encontrada en build/"; exit 1)

      - name: Deploy prebuilt artifact to SWA (skip Oryx)
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_artifact_location: "frontend/build"   # artefacto ya compilado (incluye la config)
          skip_app_build: true                      # NO reconstruir con Oryx
